name: Publish

on:
  push:
    branches:
      - master

jobs:
  publish:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1
      with:
          fetch-depth: 1

    - name: Setup Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 12.x

    - name: Cache node modules
      uses: actions/cache@v1
      with:
          path: ~/.cache/yarn
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
            ${{ runner.os }}-yarn-

    - name: Install and build
      run: |
        yarn install
        yarn build

    - name: Github release
      run: |
        git config --global user.name yeojongki
        git config --global user.email kk597@sina.com
        echo git remote -v
        yarn run release
        git push --follow-tags origin master

    - name: Publish to NPM
      run: |
        npm config set //registry.npmjs.org/:_authToken=$NPM_AUTH_TOKEN
        npm publish
      env:
        NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
