name: Test

on:
  push:
    branches:
      - dev
  pull_request:
    branches-ignore:
      - master

jobs:
  lint:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1
      with:
          fetch-depth: 1

    - name: Setup Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 12.x

    - name: Cache node modules
      uses: actions/cache@v1
      with:
          path: ~/.cache/yarn
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
            ${{ runner.os }}-yarn-

    - name: Install and test
      run: |
        yarn install
        yarn test
    
    - name: Push to master
      run: |
        git fetch
        git checkout master
        git merge dev
        git push
